# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kasugai.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkasugai.proto\x12\x07kasugai\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\x82\x01\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.kasugai.HelloRequest\x1a\x13.kasugai.HelloReply\"\x00\x12=\n\rSayHelloAgain\x12\x15.kasugai.HelloRequest\x1a\x13.kasugai.HelloReply\"\x00\x42\x18Z\x16KasugaiService/kasugaib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kasugai_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\026KasugaiService/kasugai'
  _HELLOREQUEST._serialized_start=26
  _HELLOREQUEST._serialized_end=54
  _HELLOREPLY._serialized_start=56
  _HELLOREPLY._serialized_end=85
  _GREETER._serialized_start=88
  _GREETER._serialized_end=218
# @@protoc_insertion_point(module_scope)
