# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kasugai_pb2 as kasugai__pb2


class BroadcastStub(object):
    """Service that houses the incoming ChatStream rpc, SendMessage rpc, and the ActiveUsers rpc.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/grpc.Broadcast/ChatStream',
                request_serializer=kasugai__pb2.Empty.SerializeToString,
                response_deserializer=kasugai__pb2.MessageResponse.FromString,
                )
        self.SendMessage = channel.unary_unary(
                '/grpc.Broadcast/SendMessage',
                request_serializer=kasugai__pb2.MessageResponse.SerializeToString,
                response_deserializer=kasugai__pb2.Empty.FromString,
                )
        self.ActiveUsers = channel.unary_unary(
                '/grpc.Broadcast/ActiveUsers',
                request_serializer=kasugai__pb2.ActiveUsersRequest.SerializeToString,
                response_deserializer=kasugai__pb2.ActiveUsersList.FromString,
                )


class BroadcastServicer(object):
    """Service that houses the incoming ChatStream rpc, SendMessage rpc, and the ActiveUsers rpc.
    """

    def ChatStream(self, request, context):
        """rpc that sends an empty message object to return the stream MessageResponse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """rpc that sends a MessageResponse object. Used to house the outgoing chat message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveUsers(self, request, context):
        """rpc for retrieving a list of active users on the server. Sends a request and returns a list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BroadcastServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=kasugai__pb2.Empty.FromString,
                    response_serializer=kasugai__pb2.MessageResponse.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=kasugai__pb2.MessageResponse.FromString,
                    response_serializer=kasugai__pb2.Empty.SerializeToString,
            ),
            'ActiveUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveUsers,
                    request_deserializer=kasugai__pb2.ActiveUsersRequest.FromString,
                    response_serializer=kasugai__pb2.ActiveUsersList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grpc.Broadcast', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Broadcast(object):
    """Service that houses the incoming ChatStream rpc, SendMessage rpc, and the ActiveUsers rpc.
    """

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/grpc.Broadcast/ChatStream',
            kasugai__pb2.Empty.SerializeToString,
            kasugai__pb2.MessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/SendMessage',
            kasugai__pb2.MessageResponse.SerializeToString,
            kasugai__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ActiveUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grpc.Broadcast/ActiveUsers',
            kasugai__pb2.ActiveUsersRequest.SerializeToString,
            kasugai__pb2.ActiveUsersList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
