# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kasugaipy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkasugaipy.proto\x12\x07kasugai\"/\n\x0f\x41\x63tiveUsersList\x12\x1c\n\x05users\x18\x01 \x03(\x0b\x32\r.kasugai.User\"\x14\n\x12\x41\x63tiveUsersRequest\"?\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12)\n\x07message\x18\x02 \x01(\x0b\x32\x18.kasugai.MessageResponse\"5\n\x0fMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\x9c\x01\n\tBroadcast\x12G\n\x0b\x43hatService\x12\x18.kasugai.MessageResponse\x1a\x18.kasugai.MessageResponse\"\x00(\x01\x30\x01\x12\x46\n\x0b\x41\x63tiveUsers\x12\x1b.kasugai.ActiveUsersRequest\x1a\x18.kasugai.ActiveUsersList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kasugaipy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIVEUSERSLIST._serialized_start=28
  _ACTIVEUSERSLIST._serialized_end=75
  _ACTIVEUSERSREQUEST._serialized_start=77
  _ACTIVEUSERSREQUEST._serialized_end=97
  _USER._serialized_start=99
  _USER._serialized_end=162
  _MESSAGERESPONSE._serialized_start=164
  _MESSAGERESPONSE._serialized_end=217
  _BROADCAST._serialized_start=220
  _BROADCAST._serialized_end=376
# @@protoc_insertion_point(module_scope)
