# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import protos.kasugai_pb2 as kasugai__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kasugai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Service definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterClient = channel.unary_unary(
                '/kasugai.ChatService/RegisterClient',
                request_serializer=kasugai__pb2.User.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.ActiveUsers = channel.unary_unary(
                '/kasugai.ChatService/ActiveUsers',
                request_serializer=kasugai__pb2.ActiveUsersRequest.SerializeToString,
                response_deserializer=kasugai__pb2.ActiveUsersList.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/kasugai.ChatService/SendMessage',
                request_serializer=kasugai__pb2.Message.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.ReceiveMessages = channel.unary_stream(
                '/kasugai.ChatService/ReceiveMessages',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.Message.FromString,
                _registered_method=True)
        self.StartVideoStream = channel.stream_unary(
                '/kasugai.ChatService/StartVideoStream',
                request_serializer=kasugai__pb2.VideoStream.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.WatchVideoStream = channel.unary_stream(
                '/kasugai.ChatService/WatchVideoStream',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.VideoStream.FromString,
                _registered_method=True)
        self.StartScreenShare = channel.stream_unary(
                '/kasugai.ChatService/StartScreenShare',
                request_serializer=kasugai__pb2.ScreenShare.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.WatchScreenShare = channel.unary_stream(
                '/kasugai.ChatService/WatchScreenShare',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.ScreenShare.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Service definitions
    """

    def RegisterClient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Text messaging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartVideoStream(self, request_iterator, context):
        """Video streaming
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchVideoStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScreenShare(self, request_iterator, context):
        """Screen sharing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchScreenShare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterClient': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterClient,
                    request_deserializer=kasugai__pb2.User.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'ActiveUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveUsers,
                    request_deserializer=kasugai__pb2.ActiveUsersRequest.FromString,
                    response_serializer=kasugai__pb2.ActiveUsersList.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=kasugai__pb2.Message.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'ReceiveMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveMessages,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.Message.SerializeToString,
            ),
            'StartVideoStream': grpc.stream_unary_rpc_method_handler(
                    servicer.StartVideoStream,
                    request_deserializer=kasugai__pb2.VideoStream.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'WatchVideoStream': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchVideoStream,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.VideoStream.SerializeToString,
            ),
            'StartScreenShare': grpc.stream_unary_rpc_method_handler(
                    servicer.StartScreenShare,
                    request_deserializer=kasugai__pb2.ScreenShare.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'WatchScreenShare': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchScreenShare,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.ScreenShare.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kasugai.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kasugai.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Service definitions
    """

    @staticmethod
    def RegisterClient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.ChatService/RegisterClient',
            kasugai__pb2.User.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.ChatService/ActiveUsers',
            kasugai__pb2.ActiveUsersRequest.SerializeToString,
            kasugai__pb2.ActiveUsersList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.ChatService/SendMessage',
            kasugai__pb2.Message.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kasugai.ChatService/ReceiveMessages',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartVideoStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kasugai.ChatService/StartVideoStream',
            kasugai__pb2.VideoStream.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchVideoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kasugai.ChatService/WatchVideoStream',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.VideoStream.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScreenShare(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/kasugai.ChatService/StartScreenShare',
            kasugai__pb2.ScreenShare.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchScreenShare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kasugai.ChatService/WatchScreenShare',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.ScreenShare.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileTransferServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendFileMetadata = channel.unary_unary(
                '/kasugai.FileTransferService/SendFileMetadata',
                request_serializer=kasugai__pb2.FileMetadata.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.SendFileChunk = channel.unary_unary(
                '/kasugai.FileTransferService/SendFileChunk',
                request_serializer=kasugai__pb2.FileChunk.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.ReceiveFileMetadata = channel.unary_unary(
                '/kasugai.FileTransferService/ReceiveFileMetadata',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.FileMetadata.FromString,
                _registered_method=True)
        self.ReceiveFileChunk = channel.unary_stream(
                '/kasugai.FileTransferService/ReceiveFileChunk',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.FileChunk.FromString,
                _registered_method=True)
        self.UploadFileToServer = channel.unary_unary(
                '/kasugai.FileTransferService/UploadFileToServer',
                request_serializer=kasugai__pb2.FileChunk.SerializeToString,
                response_deserializer=kasugai__pb2.Ack.FromString,
                _registered_method=True)
        self.DownloadFileFromServer = channel.unary_stream(
                '/kasugai.FileTransferService/DownloadFileFromServer',
                request_serializer=kasugai__pb2.Id.SerializeToString,
                response_deserializer=kasugai__pb2.FileChunk.FromString,
                _registered_method=True)


class FileTransferServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendFileMetadata(self, request, context):
        """P2P file transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFileChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveFileMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveFileChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFileToServer(self, request, context):
        """Server to user file transfer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFileFromServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFileMetadata,
                    request_deserializer=kasugai__pb2.FileMetadata.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'SendFileChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFileChunk,
                    request_deserializer=kasugai__pb2.FileChunk.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'ReceiveFileMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveFileMetadata,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.FileMetadata.SerializeToString,
            ),
            'ReceiveFileChunk': grpc.unary_stream_rpc_method_handler(
                    servicer.ReceiveFileChunk,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.FileChunk.SerializeToString,
            ),
            'UploadFileToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFileToServer,
                    request_deserializer=kasugai__pb2.FileChunk.FromString,
                    response_serializer=kasugai__pb2.Ack.SerializeToString,
            ),
            'DownloadFileFromServer': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFileFromServer,
                    request_deserializer=kasugai__pb2.Id.FromString,
                    response_serializer=kasugai__pb2.FileChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kasugai.FileTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kasugai.FileTransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileTransferService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.FileTransferService/SendFileMetadata',
            kasugai__pb2.FileMetadata.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFileChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.FileTransferService/SendFileChunk',
            kasugai__pb2.FileChunk.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveFileMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.FileTransferService/ReceiveFileMetadata',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.FileMetadata.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveFileChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kasugai.FileTransferService/ReceiveFileChunk',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadFileToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kasugai.FileTransferService/UploadFileToServer',
            kasugai__pb2.FileChunk.SerializeToString,
            kasugai__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFileFromServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kasugai.FileTransferService/DownloadFileFromServer',
            kasugai__pb2.Id.SerializeToString,
            kasugai__pb2.FileChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
